# Generated by Django 3.2.9 on 2021-11-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Electronic', 'Electronic'), ('Dairy', 'Dairy'), ('Snack', 'Snack'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
