# Generated by Django 3.2.9 on 2021-12-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0002_auto_20211126_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='rate',
            new_name='price',
        ),
        migrations.AddField(
            model_name='items',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronic', 'Electronic'), ('Car', 'Car'), ('Outdoor', 'Outdoor'), ('Maintenance', 'Maintenance'), ('Book', 'Book'), ('Other', 'Other')], max_length=20),
        ),
    ]
