# Generated by Django 3.2.9 on 2021-12-06 01:46

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0004_rename_price_items_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
