# Generated by Django 3.2.9 on 2021-12-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0005_auto_20211205_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='items',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
