# Generated by Django 3.2.9 on 2021-12-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0006_auto_20211205_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.ImageField(default=0, upload_to='user_img'),
            preserve_default=False,
        ),
    ]
