# Generated by Django 3.2.9 on 2021-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rent_Anything', '0007_items_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='img',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
